### ISSUE TITLE
Build fails on 32 bit machine

### ISSUE THREAD

**Issue by austriancoder** [mickael-guene/umeq#7]
[ 45%] Building ASM object src/target/arm/CMakeFiles/arm_target.dir/syscall/i386/clone_asm.S.o
[ 47%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/i386/clone.c.o
[ 48%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/i386/ptrace.c.o
[ 49%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_syscall.c.o
[ 50%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_brk.c.o
[ 51%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_clone.c.o
[ 52%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_mmap.c.o
[ 54%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_ptrace.c.o
/home/christian/projects/umeq/src/target/arm/syscall/arm_ptrace.c: In function ‘is_syscall_stop’:
/home/christian/projects/umeq/src/target/arm/syscall/arm_ptrace.c:128:11: warning: implicit declaration of function ‘syscall’ [-Wimplicit-function-declaration]
     res = syscall(SYS_ptrace, PTRACE_GETSIGINFO, pid, 0, &siginfo);
           ^~~~~~~
[ 55%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_uname.c.o
[ 56%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_open.c.o
[ 57%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_syscall_stat.c.o
[ 58%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_signal.c.o
[ 59%] Building C object src/target/arm/CMakeFiles/arm_target.dir/syscall/arm_readlink.c.o
[ 60%] Building C object src/target/arm/CMakeFiles/arm_target.dir/i386/utils.c.o
[ 62%] Linking C static library libarm_target.a
[ 62%] Built target arm_target
[ 63%] Building C object src/syscall/CMakeFiles/syscall32_32.dir/adapters/guest32_to_neutral32_adapter.c.o
/home/christian/projects/umeq/src/syscall/adapters/guest32_to_neutral32_adapter.c: In function ‘execve_neutral’:
/home/christian/projects/umeq/src/syscall/adapters/guest32_to_neutral32_adapter.c:181:15: warning: implicit declaration of function ‘parse_shebang’ [-Wimplicit-function-declaration]
         res = parse_shebang(filename, &i_name, &i_arg);
               ^~~~~~~~~~~~~
/home/christian/projects/umeq/src/syscall/adapters/guest32_to_neutral32_adapter.c:198:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         ptr[index++] = filename;
                      ^
[ 64%] Building C object src/syscall/CMakeFiles/syscall32_32.dir/adapters/shebang.c.o
[ 65%] Building C object src/syscall/CMakeFiles/syscall32_32.dir/i386/syscall_neutral_32.c.o
[ 66%] Building C object src/syscall/CMakeFiles/syscall32_32.dir/i386/syscall_i386_stat.c.o
[ 67%] Linking C static library libsyscall32_32.a
[ 67%] Built target syscall32_32
[ 68%] Building C object src/CMakeFiles/umeq-arm.dir/main.c.o
[ 70%] Building ASM object src/CMakeFiles/umeq-arm.dir/i386/start.S.o
[ 71%] Building C object src/CMakeFiles/umeq-arm.dir/i386/umeq.c.o
[ 72%] Linking C executable umeq-arm
syscall/libsyscall32_32.a(guest32_to_neutral32_adapter.c.o): In function `keyctl_neutral':
/home/christian/projects/umeq/src/syscall/adapters/guest32_to_neutral32_adapter.c:316: undefined reference to `syscall_neutral_64'
collect2: error: ld returned 1 exit status
src/CMakeFiles/umeq-arm.dir/build.make:145: recipe for target 'src/umeq-arm' failed
make[2]: *** [src/umeq-arm] Error 1
CMakeFiles/Makefile2:114: recipe for target 'src/CMakeFiles/umeq-arm.dir/all' failed
make[1]: *** [src/CMakeFiles/umeq-arm.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mickael-guene** [comment]
due to 182d5d2 because of a bad copy paste
